#!/usr/bin/env sh

# npm test                           # To run all test files
# npm test spec/MyComponent.spec.js  # To run just a single test file

if [ -z $1 ]; then
  npx rollup -c rollup.test.config.js
else
  npx rollup -c rollup.test.config.js -i $1
fi

if [ $? == 0 ]; then
  npx jasmine
fi